FROM ubuntu:20.04

RUN apt-get update && \
    apt-get -y install gcc mono-mcs librdkafka-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /src/

COPY ./producer/producer.c /src/
COPY ./producer/random.h /src/

RUN gcc producer.c -o producer -lrdkafka -fopenmp -lm

CMD ["./producer"]
